
Teste_GestorAreaConhecimento:
	g++ -std=c++23 -c CCodigoAreaConhecimento.cpp
	g++ -std=c++23 -c CGestorAreaConhecimento.cpp
	g++ -std=c++23 -c Teste_GestorAreaConhecimento.cpp
	g++ -std=c++23 CCodigoAreaConhecimento.o CGestorAreaConhecimento.o Teste_GestorAreaConhecimento.o -o Teste_GestorAreaConhecimento
	mv Teste_GestorAreaConhecimento ../../test

Teste_GestorCodigoDisciplina:
	#g++ -c CVerificaPadrao.h
	g++ -std=c++23 -c CCodigoDisciplina.cpp
	g++ -std=c++23 -c CGestorCodigoDisciplina.cpp
	g++ -std=c++23 -c Teste_GestorCodigoDisciplina.cpp
	g++ -std=c++23 CCodigoDisciplina.o CGestorCodigoDisciplina.o Teste_GestorCodigoDisciplina.o -o Teste_GestorCodigoDisciplina
	mv Teste_GestorCodigoDisciplina ../../test

Teste_EmentaDisciplina:
	g++ -std=c++23 -c CCodigoDisciplina.cpp
	g++ -std=c++23 -c CEmentaDisciplina.cpp
	g++ -std=c++23 -c Teste_EmentaDisciplina.cpp
	g++  -std=c++23 CCodigoDisciplina.o CEmentaDisciplina.o Teste_EmentaDisciplina.o -o Teste_EmentaDisciplina
	mv Teste_EmentaDisciplina ../../test
